// SPDX-License-Identifier: MIT

int main(){
  printf("Look, no license!");
}
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
// nothing new
