# SPDX-License-Identifier: MIT
---
name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "demos/**"
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  clone-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      checks: write
      statuses: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Build devcontainer image
        run: |
          docker build \
            --file demos/env/Dockerfile \
            --tag wg-aerospace-copilot-dev \
            .

      - name: Prep cross environment
        run: |
          docker run --rm \
            -e HOST_UID="$(id -u)" \
            -e HOST_GID="$(id -g)" \
            -v "${{ github.workspace }}:/workspaces/wg-aerospace" \
            -w /workspaces/wg-aerospace/demos/copilot/src/monitors \
            wg-aerospace-copilot-dev \
            make prep_cross env-debug

      - name: Build
        run: |
          docker run --rm \
            -e HOST_UID="$(id -u)" \
            -e HOST_GID="$(id -g)" \
            -v "${{ github.workspace }}:/workspaces/wg-aerospace" \
            -w /workspaces/wg-aerospace/demos/copilot/src/monitors \
            wg-aerospace-copilot-dev \
            make
          file demos/copilot/src/monitors/main_syslog_time # Verify built file exists

      - name: Build Cross Target
        run: |
          docker run --rm \
            -e HOST_UID="$(id -u)" \
            -e HOST_GID="$(id -g)" \
            -v "${{ github.workspace }}:/workspaces/wg-aerospace" \
            -w /workspaces/wg-aerospace/demos/copilot/src/monitors \
            wg-aerospace-copilot-dev \
            make main_syslog_time_cross
          file demos/copilot/src/monitors/main_syslog_time_cross # Verify built file exists

      - name: Test Cross Target
        run: |
          file demos/copilot/src/monitors/main_syslog_time_cross # Verify built file exists
          # Internal wrapper script for CI run is set to 30sec timeout so this should force a fail set to 20s
          timeout 20 docker run --rm \
            -e HOST_UID="$(id -u)" \
            -e HOST_GID="$(id -g)" \
            -v "${{ github.workspace }}:/workspaces/wg-aerospace" \
            -w /workspaces/wg-aerospace/demos/copilot/src/monitors \
            wg-aerospace-copilot-dev \
            make main_syslog_time_cross_run_ci

      - name: Test
        run: |
          docker run --rm \
            -e HOST_UID="$(id -u)" \
            -e HOST_GID="$(id -g)" \
            -v "${{ github.workspace }}:/workspaces/wg-aerospace" \
            -w /workspaces/wg-aerospace/demos/copilot/src/monitors \
            wg-aerospace-copilot-dev \
            make test

      # Docs - https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#github-action-to-publish-test-results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@567cc7f8dcea3eba5da355f6ebc95663310d8a07 # v2.17.0
        if: always()
        with:
          files: |
            demos/test-results/**/*.xml
            demos/test-results/**/*.trx
            demos/test-results/**/*.json
