# SPDX-FileCopyrightText: 2025-2026 wucke13
#
# SPDX-License-Identifier: Apache-2.0

on:
  pull_request:
    paths:
      - .github/workflows/meta.yaml
      - demos/**
  push:
    branches:
      - master

permissions:
  contents: read
  packages: read

defaults:
  run:
    working-directory: demos/AvioNix-demo

jobs:
  check-workflow-packages:
    name: Check workflow derivation coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # checkout full tree
          fetch-depth: 0
          persist-credentials: false
      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: elisa-wg-aerospace
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Checking each commit to have its derivations covered by CI
        run: nix run .#check-commits -- nix run .#update-ci -- --check
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # checkout full tree
          fetch-depth: 0
          persist-credentials: false
      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: elisa-wg-aerospace
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Checking each commit to be properly formatted
        run: nix run .#check-commits -- nix build --option log-lines 1000000 .\#checks.x86_64-linux.formatting
  check-licenses:
    name: Check licenses using reuse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # checkout full tree
          persist-credentials: false
          fetch-depth: 0
      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: elisa-wg-aerospace
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Checking each commit to be merged for proper declaration of licenses
        run: >
          nix shell .#check-commits nixpkgs#reuse --command
          reuse lint
