# SPDX-FileCopyrightText: 2025-2026 wucke13
#
# SPDX-License-Identifier: Apache-2.0

on:
  pull_request:
    paths:
      - .github/workflows/nix.yaml
      - demos/**
  push:
    branches:
      - master

defaults:
  run:
    working-directory: demos/AvioNix-demo

permissions:
  contents: read

jobs:
  flake-show:
    name: nix flake show
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          # checkout full tree
          fetch-depth: 0
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: elisa-wg-aerospace
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Show flake outputs
        run: nix flake show --quiet

  check-commits:
    name: Check commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CHECK_COMMAND:
          - nix fmt -- --ci
          - reuse lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          # checkout full tree
          fetch-depth: 0
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: elisa-wg-aerospace
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Checking each commit
        run: nix shell --inputs-from . .#check-commits nixpkgs#reuse --command ${{ matrix.CHECK_COMMAND }}

  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      # The default image contains dozens of gigabytes of tools. NixOS config builds get big. Thus,
      # remove unused tools (Nix provides for all we need!) to get some space.
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: elisa-wg-aerospace
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check

  build:
    name: nix build
    needs: [check-commits, flake-check]
    strategy:
      matrix:
        RUNNER:
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
    runs-on: ${{ matrix.RUNNER }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: elisa-wg-aerospace
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run --inputs-from . nixpkgs#nix-fast-build -- --flake .#ciJobs --no-nom --skip-cached --result-file result-junit.xml --result-format junit
      - name: Test Summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2.6
        with:
          paths: "demos/AvioNix-demo/result-junit.xml"
        if: always()
